export enum EstadoPedido {
  BORRADOR = 'BORRADOR',
  EN_CONFIGURACION = 'EN_CONFIGURACION',
  EN_RECOLECCION = 'EN_RECOLECCION',
  EN_REVISION = 'EN_REVISION',
  EN_PRODUCCION = 'EN_PRODUCCION',
  CERRADO = 'CERRADO',
  ENTREGADO = 'ENTREGADO',
  CANCELADO = 'CANCELADO',
}